### ISSUE TITLE
crash in stb_truetype

### ISSUE THREAD

**Issue by jb55** [jb55/lnvis#5]
Whenever I filter the node `KRYPTO.KOELN` I crash:

```
lnvis: deps/nanovg/stb_truetype.h:1700: stbtt__new_active: Assertion `z != ((void *)0)' failed.
```

Very strange...

**Comment by jb55** [comment]
looks like this happens when it tries to render emojis?

bt:

```
#4  0x000000000041add1 in stbtt__new_active (userdata=0xc7b720, start_point=-13, off_x=1, e=<optimized out>, hh=<synthetic pointer>) at deps/nanovg/stb_truetype.h:1700
#5  stbtt__rasterize_sorted_edges (result=result@entry=0x7ffe62c0fe80, e=<optimized out>, n=<optimized out>, off_x=off_x@entry=1, off_y=off_y@entry=-13, 
    userdata=userdata@entry=0xc7b720, vsubsample=1) at deps/nanovg/stb_truetype.h:2111
#6  0x000000000041e78d in stbtt__rasterize (userdata=0xc7b720, invert=1, off_y=-13, off_x=1, shift_y=0, shift_x=0, scale_y=0.00645392621, scale_x=0, 
    windings=<optimized out>, wcount=<optimized out>, pts=<optimized out>, result=0x7ffe62c0fe80) at deps/nanovg/stb_truetype.h:2305
#7  stbtt_Rasterize (result=result@entry=0x7ffe62c0fe80, flatness_in_pixels=flatness_in_pixels@entry=0.349999994, vertices=0xc5ab20, num_verts=num_verts@entry=952, 
    scale_x=scale_x@entry=0.00645392621, scale_y=scale_y@entry=0.00645392621, shift_x=shift_x@entry=0, shift_y=shift_y@entry=0, x_off=1, y_off=-13, 
    invert=invert@entry=1, userdata=0xc7b720) at deps/nanovg/stb_truetype.h:2414
#8  0x000000000041eb28 in stbtt_MakeGlyphBitmapSubpixel (info=info@entry=0xc59380, output=0xc8a1ba "", out_w=15, out_h=16, out_stride=512, scale_x=0.00645392621, 
    scale_y=0.00645392621, shift_x=shift_x@entry=0, shift_y=shift_y@entry=0, glyph=glyph@entry=208) at deps/nanovg/stb_truetype.h:2481
#9  0x000000000041eb4d in stbtt_MakeGlyphBitmap (info=info@entry=0xc59380, output=<optimized out>, out_w=<optimized out>, out_h=<optimized out>, 
    out_stride=<optimized out>, scale_x=<optimized out>, scale_y=<optimized out>, glyph=glyph@entry=208) at deps/nanovg/stb_truetype.h:2488
#10 0x0000000000420ae5 in fons__tt_renderGlyphBitmap (font=font@entry=0xc59380, output=<optimized out>, outWidth=<optimized out>, outHeight=<optimized out>, 
    outStride=<optimized out>, scaleX=<optimized out>, scaleY=<optimized out>, glyph=glyph@entry=208) at deps/nanovg/fontstash.h:304
#11 0x0000000000420df1 in fons__getGlyph (stash=stash@entry=0xc7b720, font=<optimized out>, codepoint=127756, isize=<optimized out>, iblur=0, bitmapOption=2)
    at deps/nanovg/fontstash.h:1137
#12 0x000000000042199c in fonsTextIterNext (stash=0xc7b720, iter=iter@entry=0x7ffe62c10060, quad=quad@entry=0x7ffe62c10040) at deps/nanovg/fontstash.h:1410
#13 0x000000000042b427 in nvgText (ctx=ctx@entry=0xbd9170, x=<optimized out>, y=<optimized out>, string=string@entry=0x7f143a523f90 "🌌BITZ2🌠", 
    end=<optimized out>, end@entry=0x0) at deps/nanovg/nanovg.c:2465
#14 0x0000000000407756 in draw_node (vg=0xbd9170, ln=0x6360a0 <ln>, node=0x7f143a523f90) at render.c:265
#15 0x000000000040793c in render_ln (ln=ln@entry=0x6360a0 <ln>) at render.c:305
#16 0x00000000004030b8 in main () at main.c:327
```

notice on frame #13: 🌌BITZ2🌠

so it's crashing on that
